{{- define "immich.server.hardcodedValues" -}}
global:
  nameOverride: server
env:
  {{ if .Values.immich.metrics.enabled }}
      IMMICH_TELEMETRY_INCLUDE: all
  {{ end }}
  {{- if .Values.immich.configuration }}
      IMMICH_CONFIG_FILE: /config/immich-config.yaml
  {{- end }}
  {{- if .Values.redis.enabled }}
      REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  DB_HOSTNAME: "{{ .Release.Name }}-postgresql"
  DB_USERNAME: "{{ .Values.postgresql.global.postgresql.auth.username }}"
  DB_DATABASE_NAME: "{{ .Values.postgresql.global.postgresql.auth.database }}"
  DB_PASSWORD: "{{ .Values.postgresql.global.postgresql.auth.password }}"
  {{- else if .Values.immich.database.existingSecret.name }}
  DB_HOSTNAME:
    valueFrom:
      secretKeyRef:
        name: {{ .Values.immich.database.existingSecret.name | quote }}
        key: {{ .Values.immich.database.existingSecret.hostnameKey | quote }}
  DB_USERNAME:
    valueFrom:
      secretKeyRef:
        name: {{ .Values.immich.database.existingSecret.name | quote }}
        key: {{ .Values.immich.database.existingSecret.usernameKey | quote }}
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: {{ .Values.immich.database.existingSecret.name | quote }}
        key: {{ .Values.immich.database.existingSecret.passwordKey | quote }}
  DB_DATABASE_NAME:
    valueFrom:
      secretKeyRef:
        name: {{ .Values.immich.database.existingSecret.name | quote }}
        key: {{ .Values.immich.database.existingSecret.databaseNameKey | quote }}
  {{- end }}

{{- if .Values.immich.configuration }}
podAnnotations:
  checksum/config: {{ .Values.immich.configuration | toYaml | sha256sum }}
{{- end }}

controller:
  strategy: RollingUpdate

service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: true
        port: 2283
        protocol: HTTP
      metrics-api:
        enabled: {{ .Values.immich.metrics.enabled }}
        port: 8081
        protocol: HTTP
      metrics-ms:
        enabled: {{ .Values.immich.metrics.enabled }}
        port: 8082
        protocol: HTTP


serviceMonitor:
  main:
    enabled: {{ .Values.immich.metrics.enabled }}
    endpoints:
      - port: metrics-api
        scheme: http
      - port: metrics-ms
        scheme: http

probes:
  liveness: &probes
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /api/server/ping
        port: http
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  readiness: *probes
  startup:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /api/server/ping
        port: http
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 30

persistence:
{{- if .Values.immich.configuration }}
  config:
    enabled: true
    type: configMap
    name: {{ .Release.Name }}-immich-config
{{- end }}
  library:
    enabled: true
    mountPath: /usr/src/app/upload
    existingClaim: {{ .Values.immich.persistence.library.existingClaim }}
{{- end }}

{{ if .Values.server.enabled }}
{{- $ctx := deepCopy . -}}
{{- $_ := get .Values "server" | mergeOverwrite $ctx.Values -}}
{{- $_ = include "immich.server.hardcodedValues" . | fromYaml | merge $ctx.Values -}}
{{- include "bjw-s.common.loader.all" $ctx }}
{{ end }}
